# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: MIT
"""agenote.completions — 静态补全脚本生成（fish / zsh / bash）。

单一真相源：COMMANDS / GLOBAL_OPTS / 配置枚举值。
generate(shell) 返回对应 shell 的完整脚本字符串（纯文本，无运行时依赖）。
"""

from __future__ import annotations

import textwrap

# ── 全局选项（main() 的顶层参数）────────────────────────────────────────
GLOBAL_OPTS = ["--domain", "--version", "-h", "--help"]

# ── 子命令表（与 cli.py commands 字典保持一致）──────────────────────────
# help 故意不补全（拦截 -h/--help 已足够，少一个噪音项）
COMMANDS: dict[str, str] = {
    "add": "添加经验卡片",
    "get": "读取卡片详情",
    "list": "列出卡片",
    "search": "全文检索",
    "fields": "列出已有字段值",
    "tags": "按标签检索",
    "memory": "管理记忆系统",
    "reindex": "重建知识库索引",
    "lint": "格式校验与报告",
    "format": "格式化卡片",
    "inbox": "快速捕获到 inbox.org",
    "inbox-archive": "把 inbox 条目归档为经验卡片",
    "stats": "知识库统计概览",
    "connect": "双向链接两张卡片",
    "update": "更新已有卡片",
    "init": "初始化知识库",
    "commit": "提交知识库变更",
    "config": "配置管理",
    "touch": "更新卡片时间戳",
    "sweep": "done/stable → stale 降级",
    "merge": "合并卡片",
    "archive": "归档卡片",
    "restore": "恢复归档卡片",
    "deduplicate": "检测重复卡片",
    "review": "审查卡片",
    "health": "知识库健康度报告",
    "gaps": "知识空白检测",
    "doctor": "环境自诊断（外部工具/配置/KB 结构）",
    "viz": "生成知识库可视化 Web 页面",
    "reconcile": "跨 agent memory 只读 reconcile",
    "dream": "从 reconcile 事实提炼候选新卡片",
    "trace": "回查 dream 候选的原始对话",
    "distill": "工作流蒸馏",
    "extract": "跨 agent 对话抽取为 Org 文件",
    "scan-memories": "只读扫描各 agent 记忆库",
    "context": "生成注入简报（只读免锁）",
    "completions": "生成 shell 补全脚本",
}

# config 的二级子命令（其余子命令无二级，暂不需要通用二级表）
CONFIG_SUBS: dict[str, str] = {
    "init": "生成带注释的配置模板",
    "show": "打印当前生效配置及来源",
}

# ── 枚举值（补全候选；从各真相源派生，不再手抄第二份）─────────────────────
# 语义枚举（DOMAIN/SHELLS/THEMES）是 CLI 自身的接口契约，留在此处即真相源；
# 数据型枚举必须跟随其真相源：源注册表（extract/memscan）、领域枚举（core）。
DOMAIN_VALUES = ["human", "agenote"]
COMPLETIONS_SHELLS = ["bash", "zsh", "fish"]
VIZ_THEMES = ["light", "dark", "auto"]


def _extract_sources() -> str:
    """reconcile/extract 的 --source 候选（extract registry + all）。"""
    from agenote.extract.base import _resolve_extractors

    return " ".join(sorted(_resolve_extractors()) + ["all"])


def _memscan_sources() -> str:
    """scan-memories 的 --source 候选（memscan 注册表 + all）。"""
    from agenote.memscan import SOURCES as MEMSCAN_REGISTRY

    return " ".join(sorted(MEMSCAN_REGISTRY) + ["all"])


def _type_values() -> str:
    from agenote.core import SEED_TYPES

    return " ".join(sorted(SEED_TYPES))


def _owner_values() -> str:
    from agenote.core import VALID_OWNERS

    return " ".join(sorted(VALID_OWNERS))


def _entry_values() -> str:
    from agenote.core import VALID_ENTRY_TYPES

    return " ".join(sorted(VALID_ENTRY_TYPES))


def _values(values) -> str:
    return " ".join(values)


def _memory_types() -> str:
    from agenote.core import MEMORY_TYPES

    return " ".join(MEMORY_TYPES)


def _subcmd_list() -> list[str]:
    return sorted(COMMANDS.keys())


# ═══════════════════════════════════════════════════════════════════════════════
# 各 shell 生成器
# ═══════════════════════════════════════════════════════════════════════════════


def _gen_fish() -> str:
    subs = " ".join(_subcmd_list())
    # 子命令级选项（简化版：够用即可，新增命令只需改 COMMANDS）
    lines = [
        "# agenote fish completion — generated by `agenote completions fish`",
        "# source: src/agenote/completions.py — do not edit by hand",
        f"complete -c agenote -n '__fish_use_subcommand' -f -a '{subs}'",
        # 全局
        "complete -c agenote -s h -l help -d '显示帮助'",
        "complete -c agenote -l version -d '显示版本号'",
        f"complete -c agenote -l domain -x -a '{' '.join(DOMAIN_VALUES)}' -d '操作域'",
        # completions 自身
        "complete -c agenote -n '__fish_seen_subcommand_from completions' -f -a 'bash zsh fish' -d '目标 shell'",
        # config 二级
        "complete -c agenote -n '__fish_seen_subcommand_from config' -f -a 'init show' -d 'config 子命令'",
        # get
        "complete -c agenote -n '__fish_seen_subcommand_from get' -l used -d '读取后记录使用'",
        # add
        f"complete -c agenote -n '__fish_seen_subcommand_from add' -l type -x -a '{_type_values()}' -d '卡片类型'",
        f"complete -c agenote -n '__fish_seen_subcommand_from add' -l owner -x -a '{_owner_values()}' -d '执行者'",
        f"complete -c agenote -n '__fish_seen_subcommand_from add' -l entry -x -a '{_entry_values()}' -d '条目语义'",
        "complete -c agenote -n '__fish_seen_subcommand_from add' -l category -d '类别'",
        "complete -c agenote -n '__fish_seen_subcommand_from add' -l tech -d '技术栈'",
        f"complete -c agenote -n '__fish_seen_subcommand_from viz' -l theme -x -a '{' '.join(VIZ_THEMES)}' -d '主题'",
        "complete -c agenote -n '__fish_seen_subcommand_from viz' -l port -d '监听端口'",
        "complete -c agenote -n '__fish_seen_subcommand_from viz' -l output -d '输出文件'",
        f"complete -c agenote -n '__fish_seen_subcommand_from reconcile' -l source -x -a '{_extract_sources()}' -d '来源'",
        "complete -c agenote -n '__fish_seen_subcommand_from reconcile' -l dry-run -d '只预览不落盘'",
        f"complete -c agenote -n '__fish_seen_subcommand_from extract' -l source -x -a '{_extract_sources()}' -d '来源'",
        "complete -c agenote -n '__fish_seen_subcommand_from extract' -l dry-run -d '只预览不落盘'",
        f"complete -c agenote -n '__fish_seen_subcommand_from scan-memories' -l source -x -a '{_memscan_sources()}' -d '来源'",
        f"complete -c agenote -n '__fish_seen_subcommand_from memory' -l type -x -a '{_memory_types()}' -d '记忆类型'",
        f"complete -c agenote -n '__fish_seen_subcommand_from memory' -l source -x -a '{_memscan_sources()}' -d '导入来源'",
        "complete -c agenote -n '__fish_seen_subcommand_from memory' -l import -d '摄取导入'",
        "complete -c agenote -n '__fish_seen_subcommand_from memory' -l conflicts -d '列出冲突队列'",
        "complete -c agenote -n '__fish_seen_subcommand_from memory' -l dry-run -d '只预览不落盘'",
        # 文件补全（lint/format 的 files 位置参数）
        "complete -c agenote -n '__fish_seen_subcommand_from lint; and not __fish_seen_subcommand_from --fix --check' -F",
        "complete -c agenote -n '__fish_seen_subcommand_from format' -F",
    ]
    return "\n".join(lines) + "\n"


def _gen_bash() -> str:
    subs = " ".join(_subcmd_list())
    ext_src = _extract_sources()
    mem_src = _memscan_sources()
    type_vals = _type_values()
    owner_vals = _owner_values()
    entry_vals = _entry_values()
    theme_vals = _values(VIZ_THEMES)
    mem_types = _memory_types()
    domain_vals = _values(DOMAIN_VALUES)
    return textwrap.dedent(
        f"""\
        # agenote bash completion — generated by `agenote completions bash`
        # source: src/agenote/completions.py — do not edit by hand
        # Usage: source this file, or copy to /etc/bash_completion.d/agenote

        _agenote_completions() {{
            local cur prev words cword
            _init_completion 2>/dev/null || {{
                COMPREPLY=()
                cur="${{COMP_WORDS[COMP_CWORD]}}"
                prev="${{COMP_WORDS[COMP_CWORD-1]}}"
                words=("${{COMP_WORDS[@]}}")
                cword=$COMP_CWORD
            }}
            local subcmds="{subs}"
            local globals="--domain --version -h --help"
            local all="$subcmds $globals"
            # 顶层：cword=1，或 words[1] 是非值型全局选项（--version/-h/--help，
            # 它们之后仍应继续补子命令）→ 补子命令 + 全局选项
            if [[ $cword -eq 1 ]] || [[ "${{words[1]}}" == --* && "${{words[1]}}" != "--domain" ]]; then
                COMPREPLY=( $(compgen -W "$all" -- "$cur") )
                return
            fi
            local sub="${{words[1]}}"
            case "$sub" in
                --domain)
                    case "$prev" in
                        --domain) COMPREPLY=( $(compgen -W "{domain_vals}" -- "$cur") );;
                        *) COMPREPLY=( $(compgen -W "$all" -- "$cur") );;
                    esac
                    ;;
                config)
                    COMPREPLY=( $(compgen -W "init show" -- "$cur") )
                    ;;
                completions)
                    COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
                    ;;
                get)
                    COMPREPLY=( $(compgen -W "--used -h --help" -- "$cur") )
                    ;;
                add)
                    case "$prev" in
                        --type) COMPREPLY=( $(compgen -W "{type_vals}" -- "$cur") );;
                        --owner) COMPREPLY=( $(compgen -W "{owner_vals}" -- "$cur") );;
                        --entry|--entry-type) COMPREPLY=( $(compgen -W "{entry_vals}" -- "$cur") );;
                        *) COMPREPLY=( $(compgen -W "--title --category --tech --type --owner --entry --entry-type --summary --stdin -h --help" -- "$cur") );;
                    esac
                    ;;
                viz)
                    case "$prev" in
                        --theme) COMPREPLY=( $(compgen -W "{theme_vals}" -- "$cur") );;
                        *) COMPREPLY=( $(compgen -W "--output --open --no-open --serve --port --theme --filter --search -h --help" -- "$cur") );;
                    esac
                    ;;
                reconcile|extract)
                    case "$prev" in
                        --source) COMPREPLY=( $(compgen -W "{ext_src}" -- "$cur") );;
                        *) COMPREPLY=( $(compgen -W "--source --dry-run --json -h --help" -- "$cur") );;
                    esac
                    ;;
                scan-memories)
                    case "$prev" in
                        --source) COMPREPLY=( $(compgen -W "{mem_src}" -- "$cur") );;
                        *) COMPREPLY=( $(compgen -W "--source --json -h --help" -- "$cur") );;
                    esac
                    ;;
                memory)
                    case "$prev" in
                        --type) COMPREPLY=( $(compgen -W "{mem_types}" -- "$cur") );;
                        --source) COMPREPLY=( $(compgen -W "{mem_src}" -- "$cur") );;
                        *) COMPREPLY=( $(compgen -W "--type --project --add --get --title --stdin --stale --touch --archive --archive-to-file --project-touch --list --scope --json --freshness --import --conflicts --source --dry-run --export --supersede --revalidate --validate -h --help" -- "$cur") );;
                    esac
                    ;;
                *) COMPREPLY=() ;;
            esac
        }}
        complete -F _agenote_completions agenote
        """
    )


def _gen_zsh() -> str:
    subs = " ".join(f'"{k}:{v}"' for k, v in sorted(COMMANDS.items()))
    # zsh 的 _arguments 值列表必须是「:消息:(a b c)」形式；「:{a,b,c}」会被当作
    # shell 代码执行（command not found），选项值补全等于没有。
    ext_src = _extract_sources()
    mem_src = _memscan_sources()
    domain_vals = _values(DOMAIN_VALUES)
    type_vals = _type_values()
    owner_vals = _owner_values()
    entry_vals = _entry_values()
    theme_vals = _values(VIZ_THEMES)
    mem_types = _memory_types()
    return textwrap.dedent(
        f"""\
        #compdef agenote
        # agenote zsh completion — generated by `agenote completions zsh`
        # source: src/agenote/completions.py — do not edit by hand
        # Usage: copy to $fpath, e.g. ~/.zsh/completions/_agenote && compinit

        _agenote() {{
            (( $+functions[_arguments] )) || autoload -U _arguments
            (( $+functions[_describe] )) || autoload -U _describe

            _arguments -C \\
                '--domain[操作域]:domain:({domain_vals})' \\
                '--version[显示版本号]' \\
                '(-h --help)-h[显示帮助]' \\
                '(-h --help)--help[显示帮助]' \\
                '1: :->subcmd' \\
                '*::arg:->args'

            case "$state" in
                subcmd)
                    _describe -t commands 'agenote commands' \\
                        '({subs})' && return 0
                    ;;
                args)
                    case $words[1] in
                        config)
                            _describe -t commands 'config subcommand' '("init:生成带注释的配置模板" "show:打印当前生效配置及来源")'
                            ;;
                        completions)
                            _describe -t values 'shell' '("bash:bash completion" "zsh:zsh completion" "fish:fish completion")'
                            ;;
                        get)
                            _arguments '--used[读取后记录使用]' '-h[显示帮助]' '--help[显示帮助]'
                            ;;
                        add)
                            _arguments \\
                                '--title[任务标题]:' \\
                                '--category[类别]:' \\
                                '--tech[技术栈]:' \\
                                '--type[类型]:类型:({type_vals})' \\
                                '--owner[执行者]:执行者:({owner_vals})' \\
                                '--entry[条目语义]:条目语义:({entry_vals})' \\
                                '--summary[一句话总结]:' \\
                                '--stdin[从标准输入读取]'
                            ;;
                        viz)
                            _arguments \\
                                '--output[输出文件]:' \\
                                '--open[生成后打开]' \\
                                '--no-open[不打开浏览器]' \\
                                '--serve[启动本地 HTTP 服务器]' \\
                                '--port[监听端口]:' \\
                                '--theme[主题]:主题:({theme_vals})'
                            ;;
                        reconcile|extract)
                            _arguments '--source[来源]:来源:({ext_src})' '--dry-run[只预览不落盘]'
                            ;;
                        scan-memories)
                            _arguments '--source[来源]:来源:({mem_src})' '--json[输出 JSON]'
                            ;;
                        memory)
                            _arguments '--type[记忆类型]:记忆类型:({mem_types})' '--source[导入来源]:来源:({mem_src})' '--import[摄取导入]' '--conflicts[列出冲突队列]' '--dry-run[只预览不落盘]'
                            ;;
                    esac
                    ;;
            esac
        }}
        _agenote "$@"
        """
    )


def generate(shell: str) -> str:
    """按 shell 名生成完整补全脚本。"""
    shell = shell.lower()
    if shell == "fish":
        return _gen_fish()
    if shell == "bash":
        return _gen_bash()
    if shell == "zsh":
        return _gen_zsh()
    raise ValueError(f"未知 shell: {shell!r}，可选: {', '.join(COMPLETIONS_SHELLS)}")
