# SPDX-FileCopyrightText: 2026 BrokenShine <xchai404@gmail.com>
#
# SPDX-License-Identifier: MIT
"""agenote.completions — 静态补全脚本生成（fish / zsh / bash）。

单一真相源：COMMANDS / GLOBAL_OPTS / 配置枚举值。
generate(shell) 返回对应 shell 的完整脚本字符串（纯文本，无运行时依赖）。
"""

from __future__ import annotations

import textwrap

# ── 全局选项（main() 的顶层参数）────────────────────────────────────────
GLOBAL_OPTS = ["--domain", "--version", "-h", "--help"]

# ── 子命令表（与 cli.py commands 字典保持一致）──────────────────────────
# help 故意不补全（拦截 -h/--help 已足够，少一个噪音项）
COMMANDS: dict[str, str] = {
    "add": "添加经验卡片",
    "get": "读取卡片详情",
    "list": "列出卡片",
    "search": "全文检索",
    "fields": "列出已有字段值",
    "tags": "按标签检索",
    "memory": "管理记忆系统",
    "reindex": "重建知识库索引",
    "lint": "格式校验与报告",
    "format": "格式化卡片",
    "inbox": "快速捕获到 inbox.org",
    "inbox-archive": "把 inbox 条目归档为经验卡片",
    "stats": "知识库统计概览",
    "connect": "双向链接两张卡片",
    "update": "更新已有卡片",
    "init": "初始化知识库",
    "commit": "提交知识库变更",
    "config": "配置管理",
    "touch": "更新卡片时间戳",
    "merge": "合并卡片",
    "archive": "归档卡片",
    "restore": "恢复归档卡片",
    "deduplicate": "检测重复卡片",
    "review": "审查卡片",
    "health": "知识库健康度报告",
    "gaps": "知识空白检测",
    "viz": "生成知识库可视化 Web 页面",
    "curate": "一键策展",
    "reconcile": "跨 agent memory 只读 reconcile",
    "dream": "从 reconcile 事实提炼候选新卡片",
    "trace": "回查 dream 候选的原始对话",
    "distill": "工作流蒸馏",
    "extract": "跨 agent 对话抽取为 Org 文件",
    "completions": "生成 shell 补全脚本",
}

# config 的二级子命令（其余子命令无二级，暂不需要通用二级表）
CONFIG_SUBS: dict[str, str] = {
    "init": "生成带注释的配置模板",
    "show": "打印当前生效配置及来源",
}

# ── 常用枚举值（补全候选用）──────────────────────────────────────────────
DOMAIN_VALUES = ["human", "agenote"]
COMPLETIONS_SHELLS = ["bash", "zsh", "fish"]
CONFIG_SOURCES = ["hermes", "opencode", "zcode", "omp", "crush", "codex", "claude", "all"]
MEMORY_TYPES = ["feedback", "project", "reference"]
OWNER_VALUES = ["human", "ai", "collab"]
TYPE_VALUES = ["debug", "refactor", "research", "workflow", "feature", "config"]
ENTRY_VALUES = ["mistake", "note", "ascended"]
STATUS_VALUES = ["done", "stable", "stale", "archived"]
VIZ_THEMES = ["light", "dark", "auto"]


def _subcmd_list() -> list[str]:
    return sorted(COMMANDS.keys())


# ═══════════════════════════════════════════════════════════════════════════════
# 各 shell 生成器
# ═══════════════════════════════════════════════════════════════════════════════


def _gen_fish() -> str:
    subs = " ".join(_subcmd_list())
    # 子命令级选项（简化版：够用即可，新增命令只需改 COMMANDS）
    lines = [
        "# agenote fish completion — generated by `agenote completions fish`",
        "# source: src/agenote/completions.py — do not edit by hand",
        f"complete -c agenote -n '__fish_use_subcommand' -f -a '{subs}'",
        # 全局
        "complete -c agenote -s h -l help -d '显示帮助'",
        "complete -c agenote -l version -d '显示版本号'",
        "complete -c agenote -l domain -x -a 'human agenote' -d '操作域'",
        # completions 自身
        "complete -c agenote -n '__fish_seen_subcommand_from completions' -f -a 'bash zsh fish' -d '目标 shell'",
        # config 二级
        "complete -c agenote -n '__fish_seen_subcommand_from config' -f -a 'init show' -d 'config 子命令'",
        # 常用枚举（按子命令条件补全）
        "complete -c agenote -n '__fish_seen_subcommand_from add' -l type -x -a 'debug refactor research workflow feature config' -d '卡片类型'",
        "complete -c agenote -n '__fish_seen_subcommand_from add' -l owner -x -a 'human ai collab' -d '执行者'",
        "complete -c agenote -n '__fish_seen_subcommand_from add' -l entry -x -a 'mistake note ascended' -d '条目语义'",
        "complete -c agenote -n '__fish_seen_subcommand_from add' -l category -d '类别'",
        "complete -c agenote -n '__fish_seen_subcommand_from add' -l tech -d '技术栈'",
        "complete -c agenote -n '__fish_seen_subcommand_from viz' -l theme -x -a 'light dark auto' -d '主题'",
        "complete -c agenote -n '__fish_seen_subcommand_from viz' -l port -d '监听端口'",
        "complete -c agenote -n '__fish_seen_subcommand_from viz' -l output -d '输出文件'",
        "complete -c agenote -n '__fish_seen_subcommand_from reconcile' -l source -x -a 'hermes opencode zcode omp crush codex claude all' -d '来源'",
        "complete -c agenote -n '__fish_seen_subcommand_from extract' -l source -x -a 'hermes opencode zcode omp crush codex claude all' -d '来源'",
        "complete -c agenote -n '__fish_seen_subcommand_from memory' -l type -x -a 'feedback project reference' -d '记忆类型'",
        # 文件补全（lint/format/commit 的 files 位置参数）
        "complete -c agenote -n '__fish_seen_subcommand_from lint; and not __fish_seen_subcommand_from --fix --check' -F",
        "complete -c agenote -n '__fish_seen_subcommand_from format' -F",
    ]
    return "\n".join(lines) + "\n"


def _gen_bash() -> str:
    subs = " ".join(_subcmd_list())
    return textwrap.dedent(
        f"""\
        # agenote bash completion — generated by `agenote completions bash`
        # source: src/agenote/completions.py — do not edit by hand
        # Usage: source this file, or copy to /etc/bash_completion.d/agenote

        _agenote_completions() {{
            local cur prev words cword
            _init_completion 2>/dev/null || {{
                COMPREPLY=()
                cur="${{COMP_WORDS[COMP_CWORD]}}"
                prev="${{COMP_WORDS[COMP_CWORD-1]}}"
                words=("${{COMP_WORDS[@]}}")
                cword=$COMP_CWORD
            }}
            local subcmds="{subs}"
            local globals="--domain --version -h --help"
            # 顶层：补子命令 + 全局选项
            if [[ $cword -eq 1 ]] || [[ "${{words[1]}}" == --* ]]; then
                local all="$subcmds $globals"
                COMPREPLY=( $(compgen -W "$all" -- "$cur") )
                return
            fi
            local sub="${{words[1]}}"
            case "$sub" in
                config)
                    COMPREPLY=( $(compgen -W "init show" -- "$cur") )
                    ;;
                completions)
                    COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
                    ;;
                add)
                    case "$prev" in
                        --type) COMPREPLY=( $(compgen -W "debug refactor research workflow feature config" -- "$cur") );;
                        --owner) COMPREPLY=( $(compgen -W "human ai collab" -- "$cur") );;
                        --entry|--entry-type) COMPREPLY=( $(compgen -W "mistake note ascended" -- "$cur") );;
                        *) COMPREPLY=( $(compgen -W "--title --category --tech --type --owner --entry --entry-type --summary --stdin -h --help" -- "$cur") );;
                    esac
                    ;;
                viz)
                    case "$prev" in
                        --theme) COMPREPLY=( $(compgen -W "light dark auto" -- "$cur") );;
                        *) COMPREPLY=( $(compgen -W "--output --open --no-open --serve --port --theme --filter --search -h --help" -- "$cur") );;
                    esac
                    ;;
                reconcile|extract)
                    case "$prev" in
                        --source) COMPREPLY=( $(compgen -W "hermes opencode zcode omp crush codex claude all" -- "$cur") );;
                        *) COMPREPLY=( $(compgen -W "--source --dry-run --json -h --help" -- "$cur") );;
                    esac
                    ;;
                memory)
                    case "$prev" in
                        --type) COMPREPLY=( $(compgen -W "feedback project reference" -- "$cur") );;
                    esac
                    ;;
                *) COMPREPLY=() ;;
            esac
        }}
        complete -F _agenote_completions agenote
        """
    )


def _gen_zsh() -> str:
    subs = " ".join(f'"{k}:{v}"' for k, v in sorted(COMMANDS.items()))
    return textwrap.dedent(
        f"""\
        #compdef agenote
        # agenote zsh completion — generated by `agenote completions zsh`
        # source: src/agenote/completions.py — do not edit by hand
        # Usage: copy to $fpath, e.g. ~/.zsh/completions/_agenote && compinit

        _agenote() {{
            local -a completions
            local -a response
            (( $+functions[_arguments] )) || autoload -U _arguments
            (( $+functions[_describe] )) || autoload -U _describe

            _arguments -C \\
                '--domain[操作域]:domain:(human agenote)' \\
                '--version[显示版本号]' \\
                '(-h --help)'{{ -h,--help}}'[显示帮助]' \\
                '1: :->subcmd' \\
                '*::arg:->args'

            case "$state" in
                subcmd)
                    _describe -t commands 'agenote commands' \\
                        '({subs})' && return 0
                    ;;
                args)
                    case $words[1] in
                        config)
                            _describe -t commands 'config subcommand' '("init:生成带注释的配置模板" "show:打印当前生效配置及来源")'
                            ;;
                        completions)
                            _describe -t values 'shell' '("bash:bash completion" "zsh:zsh completion" "fish:fish completion")'
                            ;;
                        add)
                            _arguments \\
                                '--title[任务标题]:' \\
                                '--category[类别]:' \\
                                '--tech[技术栈]:' \\
                                '--type[类型]:{{debug,refactor,research,workflow,feature,config}}' \\
                                '--owner[执行者]:{{human,ai,collab}}' \\
                                '--entry[条目语义]:{{mistake,note,ascended}}' \\
                                '--summary[一句话总结]:' \\
                                '--stdin[从标准输入读取]'
                            ;;
                        viz)
                            _arguments \\
                                '--output[输出文件]:' \\
                                '--open[生成后打开]' \\
                                '--no-open[不打开浏览器]' \\
                                '--serve[启动本地 HTTP 服务器]' \\
                                '--port[监听端口]:' \\
                                '--theme[主题]:{{light,dark,auto}}'
                            ;;
                        reconcile|extract)
                            _arguments '--source[来源]:{{hermes,opencode,zcode,omp,crush,codex,claude,all}}' '--dry-run[只预览不落盘]'
                            ;;
                    esac
                    ;;
            esac
        }}
        _agenote "$@"
        """
    )


def generate(shell: str) -> str:
    """按 shell 名生成完整补全脚本。"""
    shell = shell.lower()
    if shell == "fish":
        return _gen_fish()
    if shell == "bash":
        return _gen_bash()
    if shell == "zsh":
        return _gen_zsh()
    raise ValueError(f"未知 shell: {shell!r}，可选: {', '.join(COMPLETIONS_SHELLS)}")
