# agenote bash completion — generated by `agenote completions bash`
# source: src/agenote/completions.py — do not edit by hand
# Usage: source this file, or copy to /etc/bash_completion.d/agenote

_agenote_completions() {
    local cur prev words cword
    _init_completion 2>/dev/null || {
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    }
    local subcmds="add archive commit completions config connect curate deduplicate distill dream extract fields format gaps get health inbox inbox-archive init lint list memory merge reconcile reindex restore review search stats tags touch trace update viz"
    local globals="--domain --version -h --help"
    # 顶层：补子命令 + 全局选项
    if [[ $cword -eq 1 ]] || [[ "${words[1]}" == --* ]]; then
        local all="$subcmds $globals"
        COMPREPLY=( $(compgen -W "$all" -- "$cur") )
        return
    fi
    local sub="${words[1]}"
    case "$sub" in
        config)
            COMPREPLY=( $(compgen -W "init show" -- "$cur") )
            ;;
        completions)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
            ;;
        add)
            case "$prev" in
                --type) COMPREPLY=( $(compgen -W "debug refactor research workflow feature config" -- "$cur") );;
                --owner) COMPREPLY=( $(compgen -W "human ai collab" -- "$cur") );;
                --entry|--entry-type) COMPREPLY=( $(compgen -W "mistake note ascended" -- "$cur") );;
                *) COMPREPLY=( $(compgen -W "--title --category --tech --type --owner --entry --entry-type --summary --stdin -h --help" -- "$cur") );;
            esac
            ;;
        viz)
            case "$prev" in
                --theme) COMPREPLY=( $(compgen -W "light dark auto" -- "$cur") );;
                *) COMPREPLY=( $(compgen -W "--output --open --no-open --serve --port --theme --filter --search -h --help" -- "$cur") );;
            esac
            ;;
        reconcile|extract)
            case "$prev" in
                --source) COMPREPLY=( $(compgen -W "hermes opencode zcode omp crush codex claude all" -- "$cur") );;
                *) COMPREPLY=( $(compgen -W "--source --dry-run --json -h --help" -- "$cur") );;
            esac
            ;;
        memory)
            case "$prev" in
                --type) COMPREPLY=( $(compgen -W "feedback project reference" -- "$cur") );;
            esac
            ;;
        *) COMPREPLY=() ;;
    esac
}
complete -F _agenote_completions agenote
