# agenote bash completion — generated by `agenote completions bash`
# source: src/agenote/completions.py — do not edit by hand
# Usage: source this file, or copy to /etc/bash_completion.d/agenote

_agenote_completions() {
    local cur prev words cword
    _init_completion 2>/dev/null || {
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    }
    local subcmds="add archive commit completions config connect deduplicate distill doctor dream extract fields format gaps get health inbox inbox-archive init lint list memory merge reconcile reindex restore review scan-memories search stats sweep tags touch trace update viz"
    local globals="--domain --version -h --help"
    local all="$subcmds $globals"
    # 顶层：cword=1，或 words[1] 是非值型全局选项（--version/-h/--help，
    # 它们之后仍应继续补子命令）→ 补子命令 + 全局选项
    if [[ $cword -eq 1 ]] || [[ "${words[1]}" == --* && "${words[1]}" != "--domain" ]]; then
        COMPREPLY=( $(compgen -W "$all" -- "$cur") )
        return
    fi
    local sub="${words[1]}"
    case "$sub" in
        --domain)
            case "$prev" in
                --domain) COMPREPLY=( $(compgen -W "human agenote" -- "$cur") );;
                *) COMPREPLY=( $(compgen -W "$all" -- "$cur") );;
            esac
            ;;
        config)
            COMPREPLY=( $(compgen -W "init show" -- "$cur") )
            ;;
        completions)
            COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
            ;;
        get)
            COMPREPLY=( $(compgen -W "--used -h --help" -- "$cur") )
            ;;
        add)
            case "$prev" in
                --type) COMPREPLY=( $(compgen -W "config debug feature refactor research workflow" -- "$cur") );;
                --owner) COMPREPLY=( $(compgen -W "ai collab human" -- "$cur") );;
                --entry|--entry-type) COMPREPLY=( $(compgen -W "ascended mistake note" -- "$cur") );;
                *) COMPREPLY=( $(compgen -W "--title --category --tech --type --owner --entry --entry-type --summary --stdin -h --help" -- "$cur") );;
            esac
            ;;
        viz)
            case "$prev" in
                --theme) COMPREPLY=( $(compgen -W "light dark auto" -- "$cur") );;
                *) COMPREPLY=( $(compgen -W "--output --open --no-open --serve --port --theme --filter --search -h --help" -- "$cur") );;
            esac
            ;;
        reconcile|extract)
            case "$prev" in
                --source) COMPREPLY=( $(compgen -W "claude codex crush omp opencode zcode all" -- "$cur") );;
                *) COMPREPLY=( $(compgen -W "--source --dry-run --json -h --help" -- "$cur") );;
            esac
            ;;
        scan-memories)
            case "$prev" in
                --source) COMPREPLY=( $(compgen -W "claude codex hermes pi reasonix zcode all" -- "$cur") );;
                *) COMPREPLY=( $(compgen -W "--source --json -h --help" -- "$cur") );;
            esac
            ;;
        memory)
            case "$prev" in
                --type) COMPREPLY=( $(compgen -W "user feedback project environment reference" -- "$cur") );;
                *) COMPREPLY=( $(compgen -W "--type --project --add --get --title --stdin --stale --touch --archive --archive-to-file --project-touch -h --help" -- "$cur") );;
            esac
            ;;
        *) COMPREPLY=() ;;
    esac
}
complete -F _agenote_completions agenote
