# agenote fish completion — generated by `agenote completions fish`
# source: src/agenote/completions.py — do not edit by hand
complete -c agenote -n '__fish_use_subcommand' -f -a 'add archive commit completions config connect curate deduplicate distill dream extract fields format gaps get health inbox inbox-archive init lint list memory merge reconcile reindex restore review search stats tags touch trace update viz'
complete -c agenote -s h -l help -d '显示帮助'
complete -c agenote -l version -d '显示版本号'
complete -c agenote -l domain -x -a 'human agenote' -d '操作域'
complete -c agenote -n '__fish_seen_subcommand_from completions' -f -a 'bash zsh fish' -d '目标 shell'
complete -c agenote -n '__fish_seen_subcommand_from config' -f -a 'init show' -d 'config 子命令'
complete -c agenote -n '__fish_seen_subcommand_from add' -l type -x -a 'debug refactor research workflow feature config' -d '卡片类型'
complete -c agenote -n '__fish_seen_subcommand_from add' -l owner -x -a 'human ai collab' -d '执行者'
complete -c agenote -n '__fish_seen_subcommand_from add' -l entry -x -a 'mistake note ascended' -d '条目语义'
complete -c agenote -n '__fish_seen_subcommand_from add' -l category -d '类别'
complete -c agenote -n '__fish_seen_subcommand_from add' -l tech -d '技术栈'
complete -c agenote -n '__fish_seen_subcommand_from viz' -l theme -x -a 'light dark auto' -d '主题'
complete -c agenote -n '__fish_seen_subcommand_from viz' -l port -d '监听端口'
complete -c agenote -n '__fish_seen_subcommand_from viz' -l output -d '输出文件'
complete -c agenote -n '__fish_seen_subcommand_from reconcile' -l source -x -a 'hermes opencode zcode omp crush codex claude all' -d '来源'
complete -c agenote -n '__fish_seen_subcommand_from extract' -l source -x -a 'hermes opencode zcode omp crush codex claude all' -d '来源'
complete -c agenote -n '__fish_seen_subcommand_from memory' -l type -x -a 'feedback project reference' -d '记忆类型'
complete -c agenote -n '__fish_seen_subcommand_from lint; and not __fish_seen_subcommand_from --fix --check' -F
complete -c agenote -n '__fish_seen_subcommand_from format' -F
